### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Ic3ly** [GudeSAT/gude-ssh-ramdisk#1]
<img width="579" alt="Screen Shot 2022-03-19 at 09 54 52" src="https://user-images.githubusercontent.com/101820800/159104083-2a56ffd2-bc40-4482-bcbd-3735cc8bf452.png">

how to fix this issue ?
Im using MP 12.3
thanks

**Comment by GudeSAT** [comment]
Please update the system to 10.15.7.

**Comment by GudeSAT** [comment]
请升级到10.15.7
